name: cppcheck RTOS-AFEC-IRQ

run-name: Cppcheck RTOS-AFEC-IRQ

on: [push]

env:
  SRC_CODE: RTOS-AFEC-IRQ/src/main.c

jobs:
  oled_cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install cppcheck
        run: |
          sudo apt install cppcheck

      - name: run cppcheck
        run: |
          cppcheck -iASF -ioled --enable=all --suppress=shiftTooManyBitsSigned --suppress=missingIncludeSystem --suppress=integerOverflow --suppress=unmatchedSuppression --suppress=unusedFunction --suppress=invalidPrintfArgType_sint --suppress=invalidPrintfArgType_uint --error-exitcode=2 ${SRC_CODE}
